repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: check-added-large-files
      - id: mixed-line-ending
        args: ['--fix', 'lf']

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: git-check

  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: black
        types: [python]

      - id: isort
        name: isort
        language: system
        entry: isort
        types: [python]

      - id: flake8
        name: flake8
        language: system
        entry: flake8
        types: [python]

      - id: mypy
        name: mypy
        language: system
        entry: bash -c 'mypy "$@"' --
        types: [python]
